### ISSUE TITLE
No Early Class

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#14] opened 2019-04-17 00:46 UTC
As the picture indicates, the no early class is not working correctly.
![Issue9NoEarlyClass](https://user-images.githubusercontent.com/43483555/56253010-97cb1b80-6088-11e9-875c-8ab782a889aa.png)
![Issue9NoEarlyClass2](https://user-images.githubusercontent.com/43483555/56253012-98fc4880-6088-11e9-940d-9b67f42b87d0.png)

**Comment by hanzhi713** [comment] 2019-04-17 02:06
Well, you're referring to the 11th schedule. Please check the first one.

**Comment by hanzhi713** [comment] 2019-04-17 02:08
BTW mine shows a different result

**Comment by hanzhi713** [comment] 2019-04-17 02:12
Oh there is indeed an issue. I'll fix that.

**Comment by hanzhi713** [comment] 2019-04-17 02:22
Should be fixed at 9293ccb0e6f44b3ff2d1858c8791434b7697d5c3.

The cause of the problem is that when there is no class during a day, day[0] will evaluate to undefined, and `refTime - undefined` will give NaN.

**Comment by hanzhi713** [comment] 2019-04-18 01:32
No Early optimized at fb5e827995544e129ff80679df44fedbdf7211d6

**Comment by hanzhi713** [comment] 2019-04-18 01:32
Should alright by now. Issue closed.

**Closed** 2019-04-18 01:32 UTC
