### ISSUE TITLE
Generating Class 2

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#25] opened 2019-05-08 22:41 UTC
Only one class should be displayed but there are ten choices as shown below.
![generating class2](https://user-images.githubusercontent.com/43483555/57413033-cb4d2180-71c0-11e9-86c7-e503ea66b6d1.png)

**Comment by hanzhi713** [comment] 2019-05-08 23:12
Duplicate of #24.

**Closed by hanzhi713** 2019-05-08 23:12 UTC
Labels: duplicate
